### ISSUE TITLE
Chunks returning empty NBT compounds

### ISSUE THREAD

**Issue by ncurran02** [Focusvity/PowerNBT#1]
At the moment, the code produces empty nbt compounds for chunks due to chunk changes.

TODO:
- [x] Look at spigot's documentation for chunks
- [x] Look through NMS codes (1.11 and 1.16) to see the changes
- [ ] Submit functional code (temporarily workaround if possible?)

**Comment by ncurran02** [comment]
```[14:24:15] [Server thread/WARN]: [PowerNBT] Can't load ChunkUtils!
java.lang.RuntimeException: no such field
	at me.dpohvar.powernbt.utils.ReflectionUtils$RefClass.findField(ReflectionUtils.java:565) ~[?:?]
	at me.dpohvar.powernbt.utils.ReflectionUtils$RefClass.findField(ReflectionUtils.java:529) ~[?:?]
	at me.dpohvar.powernbt.utils.ChunkUtils.<init>(ChunkUtils.java:54) ~[?:?]
	at me.dpohvar.powernbt.utils.ChunkUtils.<clinit>(ChunkUtils.java:20) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainerChunk.readTag(NBTContainerChunk.java:37) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainerChunk.readTag(NBTContainerChunk.java:10) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:103) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:139) ~[?:?]
	at me.dpohvar.powernbt.command.action.ActionView.execute(ActionView.java:65) ~[?:?]
	at me.dpohvar.powernbt.command.CommandNBT.command(CommandNBT.java:85) ~[?:?]
	at me.dpohvar.powernbt.command.Command.onCommand(Command.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1692) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1535) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[14:24:15] [Server thread/WARN]: [PowerNBT] Exception on command: nbt
java.lang.NullPointerException: null
	at me.dpohvar.powernbt.utils.ChunkUtils.getChunkLoader(ChunkUtils.java:109) ~[?:?]
	at me.dpohvar.powernbt.utils.ChunkUtils.readChunk(ChunkUtils.java:122) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainerChunk.readTag(NBTContainerChunk.java:37) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainerChunk.readTag(NBTContainerChunk.java:10) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:103) ~[?:?]
	at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:139) ~[?:?]
	at me.dpohvar.powernbt.command.action.ActionView.execute(ActionView.java:65) ~[?:?]
	at me.dpohvar.powernbt.command.CommandNBT.command(CommandNBT.java:85) ~[?:?]
	at me.dpohvar.powernbt.command.Command.onCommand(Command.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1692) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1535) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-b5a13e6-00bff02]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]```
